### PR TITLE
Friendships v1 feature

### PR DESCRIPTION
**Pull request by Blaise-Shyaka**
In this pull request I have done the following:
- Generated a Friendship model and added associations with the User model
- Added accept and reject member routes to the friendships resource
- Created a friendships controller and added create, accept, and reject actions
- Added views to display friendship requests and invitations
- Modified Users#index views to allow users to send invites or accept/reject friendships

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello @Blaise-Shyaka, Great job! 👏  Both of you have done well on this project.
Let's make a few changes, and we will be done.

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review.

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [x]  User model should contain `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] Clicking on Friends link without logging in throws an error, kindly fix this.

- [x] On all user's page, Accept or Reject Request links are not working.

- [x] There is a button to invite user to friendship on the users' list page 👍  and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- [x] Posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

This article can come in handy as a hint: [friendships-in-activerecord](https://smartfunnycool.com/friendships-in-activerecord/).

- [x] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Affected files: `friendships/index.html.erb, users/index.html.erb and layouts/application.html.erb` **The Resources below can come in handy**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- [x] By now you should update your readme file to reflect your changes.

- [x] Your GitHub Actions aren't running, kindly fix this.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 

Great job so far @Blaise-Shyaka :clap: :clap: :clap: :clap:, thanks for working on the required changes :hammer: :wrench:  by the previous TSE, now you still have some minor :small_blue_diamond:  issues to fix so we can approve :checkered_flag:  your project.

## Required Changes:

- [x] the current user should not be able to send an invitation to himself, if you visit your own profile you will see a send invite button please hide it for current users.

- [x] Rejecting a friendship should remove the record on the Friendship table, in my case, the friend is still there and also I can't resent the friend invitation again, please fix that.
image
image

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_Please if you have a question or need help don't hesitate to contact me on slack._

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] I get this error whenever I click on the reject button, Let's fix it



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
